/**
 * Categorias padrão e dados de exemplo para demonstração
 */
import type { Category, Transaction, Account, Investment, Goal } from "./types";

export const CATEGORIES: Category[] = [
  { id: "cat-1", name: "Alimentação", icon: "fork.knife", color: "#F97316" },
  { id: "cat-2", name: "Transporte", icon: "car.fill", color: "#3B82F6" },
  { id: "cat-3", name: "Moradia", icon: "building.2.fill", color: "#8B5CF6" },
  { id: "cat-4", name: "Saúde", icon: "heart.fill", color: "#EF4444" },
  { id: "cat-5", name: "Educação", icon: "graduationcap.fill", color: "#06B6D4" },
  { id: "cat-6", name: "Lazer", icon: "gamecontroller.fill", color: "#EC4899" },
  { id: "cat-7", name: "Compras", icon: "cart.fill", color: "#F59E0B" },
  { id: "cat-8", name: "Salário", icon: "banknote.fill", color: "#22C55E" },
  { id: "cat-9", name: "Freelance", icon: "star.fill", color: "#14B8A6" },
  { id: "cat-10", name: "Outros", icon: "tag.fill", color: "#64748B" },
];

const today = new Date();
const thisMonth = today.getMonth();
const thisYear = today.getFullYear();

function dateStr(daysAgo: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
}

export const SAMPLE_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-1",
    type: "income",
    amount: 8500,
    description: "Salário",
    date: dateStr(1),
    categoryId: "cat-8",
    accountId: "acc-1",
    tags: [],
    isRecurring: true,
    createdAt: dateStr(1),
    updatedAt: dateStr(1),
  },
  {
    id: "tx-2",
    type: "expense",
    amount: 1200,
    description: "Aluguel",
    date: dateStr(2),
    categoryId: "cat-3",
    accountId: "acc-1",
    tags: [],
    isRecurring: true,
    createdAt: dateStr(2),
    updatedAt: dateStr(2),
  },
  {
    id: "tx-3",
    type: "expense",
    amount: 450,
    description: "Supermercado Extra",
    date: dateStr(3),
    categoryId: "cat-1",
    accountId: "acc-1",
    tags: ["mercado"],
    isRecurring: false,
    createdAt: dateStr(3),
    updatedAt: dateStr(3),
  },
  {
    id: "tx-3b",
    type: "expense",
    amount: 58.9,
    description: "iFood - Almoço",
    date: dateStr(2),
    categoryId: "cat-1",
    accountId: "acc-1",
    tags: [],
    isRecurring: false,
    createdAt: dateStr(2),
    updatedAt: dateStr(2),
  },
  {
    id: "tx-3c",
    type: "expense",
    amount: 32,
    description: "99 - Corrida",
    date: dateStr(2),
    categoryId: "cat-2",
    accountId: "acc-1",
    tags: [],
    isRecurring: false,
    createdAt: dateStr(2),
    updatedAt: dateStr(2),
  },
  {
    id: "tx-4",
    type: "expense",
    amount: 89.9,
    description: "Uber - Trabalho",
    date: dateStr(3),
    categoryId: "cat-2",
    accountId: "acc-1",
    tags: [],
    isRecurring: false,
    createdAt: dateStr(3),
    updatedAt: dateStr(3),
  },
  {
    id: "tx-5",
    type: "income",
    amount: 2500,
    description: "Freelance - Projeto Web",
    date: dateStr(5),
    categoryId: "cat-9",
    accountId: "acc-2",
    tags: ["freelance"],
    isRecurring: false,
    createdAt: dateStr(5),
    updatedAt: dateStr(5),
  },
  {
    id: "tx-5b",
    type: "expense",
    amount: 45,
    description: "Rappi - Jantar",
    date: dateStr(6),
    categoryId: "cat-1",
    accountId: "acc-1",
    tags: [],
    isRecurring: false,
    createdAt: dateStr(6),
    updatedAt: dateStr(6),
  },
  {
    id: "tx-5c",
    type: "expense",
    amount: 49.9,
    description: "Netflix - Assinatura",
    date: dateStr(6),
    categoryId: "cat-6",
    accountId: "acc-3",
    tags: [],
    isRecurring: true,
    createdAt: dateStr(6),
    updatedAt: dateStr(6),
  },
  {
    id: "tx-5d",
    type: "expense",
    amount: 21.9,
    description: "Spotify Premium",
    date: dateStr(6),
    categoryId: "cat-6",
    accountId: "acc-3",
    tags: [],
    isRecurring: true,
    createdAt: dateStr(6),
    updatedAt: dateStr(6),
  },
  {
    id: "tx-6",
    type: "expense",
    amount: 350,
    description: "Plano de Saúde",
    date: dateStr(7),
    categoryId: "cat-4",
    accountId: "acc-1",
    tags: [],
    isRecurring: true,
    createdAt: dateStr(7),
    updatedAt: dateStr(7),
  },
  {
    id: "tx-7",
    type: "expense",
    amount: 199,
    description: "Curso Udemy",
    date: dateStr(10),
    categoryId: "cat-5",
    accountId: "acc-3",
    tags: ["educação"],
    isRecurring: false,
    createdAt: dateStr(10),
    updatedAt: dateStr(10),
  },
  {
    id: "tx-8",
    type: "expense",
    amount: 280,
    description: "Restaurante Japonês",
    date: dateStr(12),
    categoryId: "cat-1",
    accountId: "acc-3",
    tags: [],
    isRecurring: false,
    createdAt: dateStr(12),
    updatedAt: dateStr(12),
  },
  {
    id: "tx-9",
    type: "expense",
    amount: 150,
    description: "Cinema + Pipoca",
    date: dateStr(14),
    categoryId: "cat-6",
    accountId: "acc-3",
    tags: [],
    isRecurring: false,
    createdAt: dateStr(14),
    updatedAt: dateStr(14),
  },
  {
    id: "tx-10",
    type: "expense",
    amount: 520,
    description: "Roupas Shopping",
    date: dateStr(15),
    categoryId: "cat-7",
    accountId: "acc-3",
    tags: ["compras"],
    isRecurring: false,
    createdAt: dateStr(15),
    updatedAt: dateStr(15),
  },
  {
    id: "tx-11",
    type: "income",
    amount: 1200,
    description: "Freelance - Design",
    date: dateStr(18),
    categoryId: "cat-9",
    accountId: "acc-2",
    tags: ["freelance"],
    isRecurring: false,
    createdAt: dateStr(18),
    updatedAt: dateStr(18),
  },
  {
    id: "tx-12",
    type: "expense",
    amount: 65,
    description: "Gasolina",
    date: dateStr(20),
    categoryId: "cat-2",
    accountId: "acc-1",
    tags: [],
    isRecurring: false,
    createdAt: dateStr(20),
    updatedAt: dateStr(20),
  },
];

export const SAMPLE_ACCOUNTS: Account[] = [
  {
    id: "acc-1",
    name: "Nubank",
    type: "checking",
    balance: 12450.5,
    currency: "BRL",
    isActive: true,
    createdAt: dateStr(90),
    updatedAt: dateStr(0),
  },
  {
    id: "acc-2",
    name: "Poupança Caixa",
    type: "savings",
    balance: 25000,
    currency: "BRL",
    isActive: true,
    createdAt: dateStr(90),
    updatedAt: dateStr(0),
  },
  {
    id: "acc-3",
    name: "Cartão Inter",
    type: "credit_card",
    balance: -1850.3,
    currency: "BRL",
    isActive: true,
    createdAt: dateStr(60),
    updatedAt: dateStr(0),
  },
];

export const SAMPLE_INVESTMENTS: Investment[] = [
  {
    id: "inv-1",
    symbol: "PETR4",
    name: "Petrobras PN",
    type: "stock",
    quantity: 100,
    averagePrice: 32.5,
    currentPrice: 38.75,
    currency: "BRL",
    broker: "XP",
    sector: "Energia",
    createdAt: dateStr(120),
    updatedAt: dateStr(0),
  },
  {
    id: "inv-2",
    symbol: "VALE3",
    name: "Vale ON",
    type: "stock",
    quantity: 50,
    averagePrice: 68.0,
    currentPrice: 72.3,
    currency: "BRL",
    broker: "XP",
    sector: "Mineração",
    createdAt: dateStr(90),
    updatedAt: dateStr(0),
  },
  {
    id: "inv-3",
    symbol: "IVVB11",
    name: "iShares S&P 500",
    type: "etf",
    quantity: 30,
    averagePrice: 280.0,
    currentPrice: 310.5,
    currency: "BRL",
    broker: "Rico",
    sector: "Internacional",
    createdAt: dateStr(60),
    updatedAt: dateStr(0),
  },
  {
    id: "inv-4",
    symbol: "BTC",
    name: "Bitcoin",
    type: "crypto",
    quantity: 0.05,
    averagePrice: 180000,
    currentPrice: 520000,
    currency: "BRL",
    broker: "Binance",
    sector: "Cripto",
    createdAt: dateStr(180),
    updatedAt: dateStr(0),
  },
  {
    id: "inv-5",
    symbol: "TESOURO SELIC",
    name: "Tesouro Selic 2029",
    type: "bond",
    quantity: 5,
    averagePrice: 14200,
    currentPrice: 14850,
    currency: "BRL",
    broker: "Tesouro Direto",
    sector: "Renda Fixa",
    createdAt: dateStr(150),
    updatedAt: dateStr(0),
  },
];

export const SAMPLE_GOALS: Goal[] = [
  {
    id: "goal-1",
    name: "Reserva de Emergência",
    description: "6 meses de despesas",
    type: "savings",
    targetAmount: 30000,
    currentAmount: 25000,
    targetDate: new Date(thisYear, 11, 31).toISOString(),
    isActive: true,
    createdAt: dateStr(180),
    updatedAt: dateStr(0),
  },
  {
    id: "goal-2",
    name: "Viagem Europa",
    description: "Férias na Europa em 2027",
    type: "savings",
    targetAmount: 20000,
    currentAmount: 8500,
    targetDate: new Date(thisYear + 1, 5, 1).toISOString(),
    isActive: true,
    createdAt: dateStr(120),
    updatedAt: dateStr(0),
  },
  {
    id: "goal-3",
    name: "Limite Alimentação",
    description: "Máximo R$ 1.500/mês",
    type: "spending_limit",
    targetAmount: 1500,
    currentAmount: 730,
    isActive: true,
    createdAt: dateStr(30),
    updatedAt: dateStr(0),
  },
];

export const ACCOUNT_TYPE_LABELS: Record<string, string> = {
  checking: "Conta Corrente",
  savings: "Poupança",
  credit_card: "Cartão de Crédito",
  investment: "Investimento",
};

export const INVESTMENT_TYPE_LABELS: Record<string, string> = {
  stock: "Ação",
  fund: "Fundo",
  etf: "ETF",
  crypto: "Cripto",
  bond: "Renda Fixa",
};

export const GOAL_TYPE_LABELS: Record<string, string> = {
  savings: "Poupança",
  spending_limit: "Limite de Gasto",
  investment: "Investimento",
};
